Areas/Admin/Controllers/AddItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Collections.Domain;
using Collections.Domain.Entities;
using Collections.Service;
using Microsoft.EntityFrameworkCore.Query;
using System.Linq;

namespace Collections.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AddItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        private static string collectionId;
        public AddItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }
        /* public IActionResult Index(string id)
         {
             if (id != null) { collectionId = id; }
             return View(dataManager.Items.GetItemsByCollectionId(collectionId));
         }*/
        public IActionResult Index(string id, string name, string sortBy)
        {
            if (id != null) { collectionId = id; }
            IQueryable<Item> items = dataManager.Items.GetItemsByCollectionId(collectionId);
            if (!String.IsNullOrEmpty(name))
            {
                items = items.Where(p => p.Name.Contains(name));
            }
            if (!String.IsNullOrEmpty(sortBy))
            {
                switch (sortBy)
                {
                    case "Datemax":
                        items = items.OrderBy(s => s.DateAdded);
                        break;
                    case "Datemin":
                        items = items.OrderByDescending(s => s.DateAdded);
                        break;
                    case "AlphAZ":
                        items = items.OrderBy(s => s.Name);
                        break;
                    case "AlphZA":
                        items = items.OrderByDescending(s => s.Name);
                        break;
                }
            }
            return View(items);
        }
        public IActionResult Edit(Guid id)
        {
            Item entity = id == default ? new Item() : dataManager.Items.GetItemById(id);
            Collection collection = dataManager.Collections.GetCollectionById(collectionId);
            GetItemFieldsNames(collectionId);
            entity.itemFields = collection.itemFields;
            entity.CollectionId = collectionId;
            if (id == null)
            {
                collection.numberOfItems += 1;
                dataManager.Collections.SaveCollection(collection);
            }
            dataManager.Items.SaveItem(entity);
            return View(entity);
        }

        public void GetItemFieldsNames(string collectionId)
        {
            Collection collection = dataManager.Collections.GetCollectionById(collectionId);
            ViewData["Num1Name"] = collection.Num1Name;
            ViewData["Num2Name"] = collection.Num2Name;
            ViewData["Num3Name"] = collection.Num3Name;
            ViewData["Input1Name"] = collection.Input1Name;
            ViewData["Input2Name"] = collection.Input2Name;
            ViewData["Input3Name"] = collection.Input3Name;
            ViewData["Textarea1Name"] = collection.Textarea1Name;
            ViewData["Textarea2Name"] = collection.Textarea2Name;
            ViewData["Textarea3Name"] = collection.Textarea3Name;
            ViewData["Date1Name"] = collection.Date1Name;
            ViewData["Date2Name"] = collection.Date2Name;
            ViewData["Date3Name"] = collection.Date3Name;
            ViewData["Checkbox1Name"] = collection.Checkbox1Name;
            ViewData["Checkbox2Name"] = collection.Checkbox2Name;
            ViewData["Checkbox3Name"] = collection.Checkbox3Name;
        }

        [HttpPost]
        public IActionResult Edit(Item model)
        {
            if (ModelState.IsValid)
            {
                model.CollectionId = collectionId;
                dataManager.Items.SaveItem(model);
                return RedirectToAction(nameof(AddItemsController.Index), nameof(AddItemsController).CutController());
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.Items.DeleteItem(id);
            return RedirectToAction(nameof(AddItemsController.Index), nameof(AddItemsController).CutController());
        }
    }
}

Areas/User/Controllers/AddItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Collections.Domain;
using Collections.Domain.Entities;
using Collections.Service;
using Microsoft.EntityFrameworkCore.Query;
using System.Linq;

namespace Collections.Areas.User.Controllers
{
    [Area("User")]
    public class AddItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        private static string collectionId;
        public AddItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }
        /* public IActionResult Index(string id)
         {
             if (id != null) { collectionId = id; }
             return View(dataManager.Items.GetItemsByCollectionId(collectionId));
         }*/
        public IActionResult Index(string id, string name, string sortBy)
        {
            if (id != null) { collectionId = id; }
            IQueryable<Item> items = dataManager.Items.GetItemsByCollectionId(collectionId);
            if (!String.IsNullOrEmpty(name))
            {
                items = items.Where(p => p.Name.Contains(name));
            }           
            if (!String.IsNullOrEmpty(sortBy))
            {                
                switch (sortBy)
                {
                    case "Datemax":
                        items = items.OrderBy(s => s.DateAdded);
                        break;
                    case "Datemin":
                        items = items.OrderByDescending(s => s.DateAdded);
                        break;
                    case "AlphAZ":
                        items = items.OrderBy(s => s.Name);
                        break;
                    case "AlphZA":
                        items = items.OrderByDescending(s => s.Name);
                        break;
                }
            }
            return View(items);
        }
        public IActionResult Edit(Guid id)
        {
            Item entity = id == default ? new Item() : dataManager.Items.GetItemById(id);
            Collection collection = dataManager.Collections.GetCollectionById(collectionId);
            GetItemFieldsNames(collectionId);
            entity.itemFields = collection.itemFields;
            entity.CollectionId = collectionId;
            if (id == null)
            {
                collection.numberOfItems += 1;
                dataManager.Collections.SaveCollection(collection);
            }           
            dataManager.Items.SaveItem(entity);
            return View(entity);
        }

        public void GetItemFieldsNames(string collectionId)
        {
            Collection collection = dataManager.Collections.GetCollectionById(collectionId);
            ViewData["Num1Name"] = collection.Num1Name;
            ViewData["Num2Name"] = collection.Num2Name;
            ViewData["Num3Name"] = collection.Num3Name;
            ViewData["Input1Name"] = collection.Input1Name;
            ViewData["Input2Name"] = collection.Input2Name;
            ViewData["Input3Name"] = collection.Input3Name;
            ViewData["Textarea1Name"] = collection.Textarea1Name;
            ViewData["Textarea2Name"] = collection.Textarea2Name;
            ViewData["Textarea3Name"] = collection.Textarea3Name;
            ViewData["Date1Name"] = collection.Date1Name;
            ViewData["Date2Name"] = collection.Date2Name;
            ViewData["Date3Name"] = collection.Date3Name;
            ViewData["Checkbox1Name"] = collection.Checkbox1Name;
            ViewData["Checkbox2Name"] = collection.Checkbox2Name;
            ViewData["Checkbox3Name"] = collection.Checkbox3Name;
        }

        [HttpPost]
        public IActionResult Edit(Item model)
        {
            if (ModelState.IsValid)
            {
                model.CollectionId = collectionId;
                dataManager.Items.SaveItem(model);
                return RedirectToAction(nameof(AddItemsController.Index), nameof(AddItemsController).CutController());
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.Items.DeleteItem(id);
            return RedirectToAction(nameof(AddItemsController.Index), nameof(AddItemsController).CutController());
        }
    }
}

Areas/User/Views/AddItems/Edit.cshtml
@model Item

<script src="~/js/ckeditor/ckeditor.js"></script>
<div>
    <div>
        <form asp-area="User" asp-controller="AddItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="itemFields" />
            <input type="hidden" asp-for="CollectionId" />
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Name"></label>
                <input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Tag"></label>
                <input asp-for="Tag" />
                <span asp-validation-for="Tag"></span>
            </div>
            @if ((Model.itemFields & 1) == 1)
            {
                <div class="div-box">
                    <label>@ViewData["Num1Name"]</label>
                    <input asp-for="Num1Value" />
                    <span asp-validation-for="Num1Value"></span>
                </div>
            }
            @if ((Model.itemFields & 2) == 2)
            {
                <div class="div-box">
                    <label>@ViewData["Num2Name"]</label>
                    <input asp-for="Num2Value" />
                    <span asp-validation-for="Num2Value"></span>
                </div>
            }
            @if ((Model.itemFields & 4) == 4)
            {
                <div class="div-box">
                    <label>@ViewData["Num3Name"]</label>
                    <input asp-for="Num3Value" />
                    <span asp-validation-for="Num3Value"></span>
                </div>
            }
            @if ((Model.itemFields & 8) == 8)
            {
                <div class="div-box">
                    <label>@ViewData["Input1Name"]</label>
                    <input asp-for="Input1Value" />
                    <span asp-validation-for="Input1Value"></span>
                </div>
            }
            @if ((Model.itemFields & 16) == 16)
            {
                <div class="div-box">
                    <label>@ViewData["Input2Name"]</label>
                    <input asp-for="Input2Value" />
                    <span asp-validation-for="Input2Value"></span>
                </div>
            }
            @if ((Model.itemFields & 32) == 32)
            {
                <div class="div-box">
                    <label>@ViewData["Input3Name"]</label>
                    <input asp-for="Input3Value" />
                    <span asp-validation-for="Input3Value"></span>
                </div>
            }
            @if ((Model.itemFields & 64) == 64)
            {
                <div class="div-box">
                    <label>@ViewData["Textarea1Name"]</label>
                    <input asp-for="Textarea1Value" />
                    <span asp-validation-for="Textarea1Value"></span>
                </div>
            }
            @if ((Model.itemFields & 128) == 128)
            {
                <div class="div-box">
                    <label>@ViewData["Textarea2Name"]</label>
                    <input asp-for="Textarea2Value" />
                    <span asp-validation-for="Textarea2Value"></span>
                </div>
            }
            @if ((Model.itemFields & 256) == 256)
            {
                <div class="div-box">
                    <label>@ViewData["Textarea3Name"]</label>
                    <input asp-for="Textarea3Value" />
                    <span asp-validation-for="Textarea3Value"></span>
                </div>
            }
            @if ((Model.itemFields & 512) == 512)
            {
                <div class="div-box">
                   <label>@ViewData["Date1Name"]</label>
                   <input asp-for="Date1Value" />
                    <span asp-validation-for="Date1Value"></span>
                </div>
            }
            @if ((Model.itemFields & 1024) == 1024)
            {
                <div class="div-box">                    
                    <label>@ViewData["Date2Name"]</label>
                    <input asp-for="Date2Value" />
                    <span asp-validation-for="Date2Value"></span>
                </div>
            }
            @if ((Model.itemFields & 2048) == 2048)
            {
                <div class="div-box">                   
                    <label>@ViewData["Date3Name"]</label>
                    <input asp-for="Date3Value" />
                    <span asp-validation-for="Date3Value"></span>
                </div>
            }
            @if ((Model.itemFields & 4096) == 4096)
            {
                <div class="div-box">
                    <label>@ViewData["Checkbox1Name"]</label>
                    <input asp-for="Checkbox1Value" />
                    <span asp-validation-for="Checkbox1Value"></span>
                </div>
            }
            @if ((Model.itemFields & 8192) == 8192)
            {
                <div class="div-box">
                    <label>@ViewData["Checkbox2Name"]</label>
                    <input asp-for="Checkbox2Value" />
                    <span asp-validation-for="Checkbox2Value"></span>
                </div>
            }
            @if ((Model.itemFields & 16384) == 16384)
            {
                <div class="div-box">
                    <label>@ViewData["Checkbox3Name"]</label>
                    <input asp-for="Checkbox3Value" />
                    <span asp-validation-for="Checkbox3Value"></span>
                </div>
            }
            <input type="submit" value="Save" />
        </form>
    </div>
</div>

Areas/User/Views/AddItems/Index.cshtml
@model IQueryable<Item>
@{
    string strTitle = "User area";
    ViewBag.Title = strTitle;
}
<style>
    .sortform {
        display: inline;
        display: inline-block;
        float: right;
    }
</style>
<script src="https://kit.fontawesome.com/163cdcd962.js" crossorigin="anonymous"></script>
<div>
    <div class="div-box">
        <a asp-area="User" asp-controller="Home" asp-action="Index">Go to list of collections</a>
    </div>
    <div class="div-box">
        <a asp-area="User" asp-controller="AddItems" asp-action="Edit" asp-route-id=""><i class="fas fa-plus-square"></i></a>
    </div>
    <div class="div-box">
        <form method="get" asp-area="User" asp-controller="AddItems" asp-action="Index" enctype="multipart/form-data">
            Name:  <input name="name" class="form-control" />
            <select size="1" name="sortBy">
                <option selected disabled>Sort by</option>
                <option value="Datemin">Date min</option>
                <option value="Datemax">Date max</option>
                <option value="AlphAZ">Alph A-Z</option>
                <option value="AlphZA">Alph Z-A</option>
            </select>
            <input type="submit" value="Filter" class="btn btn-default" />
        </form>
    </div>
    <table width="100%" cellpadding="5">
        @foreach (Item i in Model)
        {
            <tr>
                <td>@i.Name</td>
                <td>@i.Tag</td>
                <td>@i.DateAdded</td>
                <td>
                    <a asp-area="User" asp-controller="AddItems" asp-action="Edit" asp-route-id="@i.Id"><i class="far fa-edit"></i></a>
                </td>
                <td>
                    <form style="display: inline-block;" id="form-@i.Id" asp-area="User" asp-controller="AddItems" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@i.Id" />
                        <a href="#" onclick="document.getElementById('form-@i.Id').submit();"><i class="fas fa-backspace"></i></a>
                    </form>
                </td>
            </tr>
        }
    </table>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Sign out" />
        </form>
    </div>
</div>