Areas/User/Controllers/ServiceItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Collections.Domain;
using Collections.Domain.Entities;
using Collections.Service;

namespace Collections.Areas.User.Controllers
{
    [Area("User")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new Collection() : dataManager.Collections.GetCollectionById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(Collection model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.Collections.SaveCollection(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.Collections.DeleteCollection(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Areas/User/Views/ServiceItems/Edit.cshtml
@model Collection
@{
    string strTitle = "Add/Edit Collection";
    ViewBag.Title = strTitle;
}
<script src="~/js/ckeditor/ckeditor.js"></script>
<div>    
    <div>
        <form asp-area="User" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ownerId" />
            <input type="hidden" asp-for="TitleImagePath" />
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="shortDescription"></label>
                <input asp-for="shortDescription" />
                <span asp-validation-for="shortDescription"></span>
            </div>
            <div>
                <label asp-for="Theme">Collection's theme</label>
                <select asp-for="Theme" asp-items="Html.GetEnumSelectList<Collection.psblThemes>()"></select>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>       
            <input type="submit" value="Save" />
        </form>
    </div>
</div>