Areas/Admin/Controllers/ServiceCollectionsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Collections.Domain;
using Collections.Domain.Entities;
using Collections.Models;
using Collections.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Collections.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceCollectionsController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        private static string ownerId;

        public ServiceCollectionsController(UserManager<IdentityUser> userMgr, DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userMgr;
        }
        public async System.Threading.Tasks.Task<IActionResult> Index(string id)
        {
            if (id != null) { ownerId = id; }
            var user = await userManager.FindByIdAsync(ownerId);
            ViewBag.currentUserName = user.UserName;
            return View(dataManager.Collections.GetUsersCollections(ownerId));
        }
        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new Collection() : dataManager.Collections.GetCollectionById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(Collection model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (model.Num1Name != null)
                {
                    model.itemFields = model.itemFields | 1;

                }
                if (model.Num2Name != null)
                {
                    model.itemFields = model.itemFields | 2;

                }
                if (model.Num3Name != null)
                {
                    model.itemFields = model.itemFields | 4;

                }
                if (model.Input1Name != null)
                {
                    model.itemFields = model.itemFields | 8;
                }
                if (model.Input2Name != null)
                {
                    model.itemFields = model.itemFields | 16;
                }
                if (model.Input3Name != null)
                {
                    model.itemFields = model.itemFields | 32;
                }
                if (model.Textarea1Name != null)
                {
                    model.itemFields = model.itemFields | 64;
                }
                if (model.Textarea2Name != null)
                {
                    model.itemFields = model.itemFields | 128;
                }
                if (model.Textarea3Name != null)
                {
                    model.itemFields = model.itemFields | 256;
                }
                if (model.Date1Name != null)
                {
                    model.itemFields = model.itemFields | 512;
                }
                if (model.Date2Name != null)
                {
                    model.itemFields = model.itemFields | 1024;
                }
                if (model.Date3Name != null)
                {
                    model.itemFields = model.itemFields | 2048;
                }
                if (model.Checkbox1Name != null)
                {
                    model.itemFields = model.itemFields | 4096;
                }
                if (model.Checkbox2Name != null)
                {
                    model.itemFields = model.itemFields | 8192;
                }
                if (model.Checkbox3Name != null)
                {
                    model.itemFields = model.itemFields | 16384;
                }
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                model.ownerId = ownerId;
                dataManager.Collections.SaveCollection(model);
                return RedirectToAction(nameof(ServiceCollectionsController.Index), nameof(ServiceCollectionsController).CutController());

            }
            return View(model);

        }
        [HttpPost]
        public IActionResult Delete(Guid id, string ownerId)
        {
            ViewBag.currentUserId = ownerId;
            dataManager.Collections.DeleteCollection(id);
            return RedirectToAction(nameof(ServiceCollectionsController.Index), nameof(ServiceCollectionsController).CutController());
        }
    }
}

Areas/Admin/Views/ServiceCollections/Edit.cshtml
@model Collection
@{
    string strTitle = "Add";
    ViewBag.Title = strTitle;
}
<script src="~/js/ckeditor/ckeditor.js"></script>
<div>    
    <div>
        <form asp-area="Admin" asp-controller="ServiceCollections" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ownerId" />
            <input type="hidden" asp-for="TitleImagePath" />
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="shortDescription"></label>
                <input asp-for="shortDescription" />
                <span asp-validation-for="shortDescription"></span>
            </div>
            <div>
                <label asp-for="Theme">Collection's theme</label>
                <select asp-for="Theme" asp-items="Html.GetEnumSelectList<Collection.psblThemes>()"></select>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="Num1Name"></label>
                <input asp-for="Num1Name" />
                <span asp-validation-for="Num1Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Num2Name"></label>
                <input asp-for="Num2Name" />
                <span asp-validation-for="Num2Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Num3Name"></label>
                <input asp-for="Num3Name" />
                <span asp-validation-for="Num3Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Input1Name"></label>
                <input asp-for="Input1Name" />
                <span asp-validation-for="Input1Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Input2Name"></label>
                <input asp-for="Input2Name" />
                <span asp-validation-for="Input2Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Input3Name"></label>
                <input asp-for="Input3Name" />
                <span asp-validation-for="Input3Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Textarea1Name"></label>
                <input asp-for="Textarea1Name" />
                <span asp-validation-for="Textarea1Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Textarea2Name"></label>
                <input asp-for="Textarea2Name" />
                <span asp-validation-for="Textarea2Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Textarea3Name"></label>
                <input asp-for="Textarea3Name" />
                <span asp-validation-for="Textarea3Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Date1Name"></label>
                <input asp-for="Date1Name" />
                <span asp-validation-for="Date1Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Date2Name"></label>
                <input asp-for="Date2Name" />
                <span asp-validation-for="Date2Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Date3Name"></label>
                <input asp-for="Date3Name" />
                <span asp-validation-for="Date3Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Checkbox1Name"></label>
                <input asp-for="Checkbox1Name" />
                <span asp-validation-for="Checkbox1Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Checkbox2Name"></label>
                <input asp-for="Checkbox2Name" />
                <span asp-validation-for="Checkbox2Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Checkbox3Name"></label>
                <input asp-for="Checkbox3Name" />
                <span asp-validation-for="Checkbox3Name"></span>
            </div>
            <input type="submit" value="Save" />
        </form>
    </div>
</div>

Areas/Admin/Views/ServiceCollections/Index.cshtml
@model IQueryable<Collection>
@{
    string strTitle = "User area";
    ViewBag.Title = strTitle;
}
<script src="https://kit.fontawesome.com/163cdcd962.js" crossorigin="anonymous"></script>
<div>
    <div>
        @ViewBag.currentUserName's colections
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceCollections" asp-action="Edit" asp-route-id=""><i class="fas fa-plus-square"></i></a>
        </div>
        <h3>Collections</h3>
        <div>
            <table width="70%" cellpadding="5">

                @foreach (Collection entity in Model)
                {
                    <tr>
                        <td>
                            <a asp-area="Admin" asp-controller="Additems" asp-action="Index" asp-route-id="@entity.Id">
                                @($"{entity.Title}")
                            </a>
                        </td>
                        <td>
                            <a asp-area="Admin" asp-controller="ServiceCollections" asp-action="Edit" asp-route-id="@entity.Id"><i class="far fa-edit"></i></a>
                        </td>
                        <td>
                            <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceCollections" asp-action="Delete" method="post">
                                <input type="hidden" name="id" value="@entity.Id" />
                                <input type="hidden" name="ownerId" value="@ViewBag.currentUserId" />
                                <a href="#" onclick="document.getElementById('form-@entity.Id').submit();"><i class="fas fa-backspace"></i></a>
                            </form>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Sign out" />
        </form>
    </div>
</div>